name: Comment on Performance

on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string
      output:
        required: true
        type: string
      pr_number:
        required: true
        type: number

permissions:
  pull-requests: write
  contents: read

jobs:
  comment-perf:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.number }}
    steps:

      - name: Download artifact
        if: ${{ inputs.output == '0' }}
        uses: dawidd6/action-download-artifact@v3
        with:
          name: perf-results
          path: ./perf-data

      - name: has_failed
        if: ${{ inputs.output != '0' }}
        id: has_failed
        run: |
         if [ -f ./perf-data/exitcode.txt ]; then
           code=$(grep exit_code ./perf-data/exitcode.txt | cut -d "=" -f 2)
           echo "exit_code=$code" >> $GITHUB_OUTPUT
         else
           echo "exit_code=0" >> $GITHUB_OUTPUT
         fi

      - name: Download artifact from CI
        id: check_file
        if: ${{ inputs.output == '0' }}
        uses: dawidd6/action-download-artifact@v3
        with:
          name: perf-results
          run_id: ${{ github.event.workflow_run.id }}
          path: ./perf-data
        continue-on-error: true

      - name: Read performance result
        if: ${{ inputs.output == '0' && steps.check_file.outcome != 'failure' }}
        id: perf
        run: |
          if [ 
          read=$(grep "read=" perf-data/result.txt | cut -d "=" -f2)
          write=$(grep "write=" perf-data/result.txt | cut -d "=" -f2)
          cycle=$(grep "cycle=" perf-data/result.txt | cut -d "=" -f2)
          echo "read=$read" >> $GITHUB_OUTPUT
          echo "write=$write" >> $GITHUB_OUTPUT
          echo "cycle=$cycle" >> $GITHUB_OUTPUT


      - name: Comment on PR
        if: ${{ inputs.output == '0' && steps.check_file.outcome != 'failure' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          pr-number:  ${{ inputs.pr_number }}
          message: |
            result :
            -  Read Miss : `${{ steps.perf.outputs.read }}`
            -  Write Miss : `${{ steps.perf.outputs.write }}`
            -  Cycles : `${{ steps.perf.outputs.cycle }}`
      
      - name: Trigger comment workflow bad 
        if: ${{ inputs.output != '0' }}
        uses: actions/github-script@v7
        with:
          script: |
            pr-number = ${{ inputs.pr_number }}
            if (prNumber) {
              await github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "✅ Tests passed avec succès ! 🎉"
              });
            } else {
              core.warning("PR non trouvée pour la branche: " + context.payload.workflow_run.head-branch);
            }     




        # uses: thollander/actions-comment-pull-request@v3
        # with:
        #   pr-number: ${{ steps.find-pr.outputs.pr-number }}
        #   message: >
        #     ${{
        #       steps.has_failed.outputs.exitcode == '1' && 'Pipeline has failed due to a decrease in performance in read' ||
        #       steps.has_failed.outputs.exitcode == '2' && 'Pipeline has failed due to a decrease in performance in write' ||
        #       steps.has_failed.outputs.exitcode == '3' && 'Pipeline has failed due to an increase for number of cycle' ||
        #      'Unknow error code'
        #     }}
