name: Comment on Performance

on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string

jobs:
  comment-perf:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Download artifact
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        uses: dawidd6/action-download-artifact@v3
        with:
          name: perf-results
          path: ./perf-data

      - name: has_failed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        id: has_failed
        run: |
         if [ -f ./perf-data/exitcode.txt ]; then
           code=$(grep exit_code ./perf-data/exitcode.txt | cut -d "=" -f 2)
           echo "exit_code=$code" >> $GITHUB_OUTPUT
         else
           echo "exit_code=0" >> $GITHUB_OUTPUT
         fi

      - name: Download artifact from CI
        id: check_file
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: dawidd6/action-download-artifact@v3
        with:
          name: perf-results
          run_id: ${{ github.event.workflow_run.id }}
          path: ./perf-data
        continue-on-error: true

      - name: Read performance result
        if: ${{ github.event.workflow_run.conclusion == 'success' && steps.check_file.outcome != 'failure' }}
        id: perf
        run: |
          if [ 
          read=$(grep "read=" perf-data/result.txt | cut -d "=" -f2)
          write=$(grep "write=" perf-data/result.txt | cut -d "=" -f2)
          cycle=$(grep "cycle=" perf-data/result.txt | cut -d "=" -f2)
          echo "read=$read" >> $GITHUB_OUTPUT
          echo "write=$write" >> $GITHUB_OUTPUT
          echo "cycle=$cycle" >> $GITHUB_OUTPUT

      - name: Find related pull request
        id: find-pr
        if: ${{ github.event.workflow_run.conclusion == 'success' && steps.check_file.outcome != 'failure' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commitSha = context.payload.workflow_run.head_sha;
            const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commitSha,
            });
            if (prs.length === 0) {
              throw new Error(`No PR found for commit ${commitSha}`);
            }
            core.setOutput('pr_number', prs[0].number);

      - name: Comment on PR
        if: ${{ github.event.workflow_run.conclusion == 'success' && steps.check_file.outcome != 'failure' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          pr_number: ${{ steps.find-pr.outputs.pr_number }}
          message: |
            result :
            -  Read Miss : `${{ steps.perf.outputs.read }}`
            -  Write Miss : `${{ steps.perf.outputs.write }}`
            -  Cycles : `${{ steps.perf.outputs.cycle }}`
      
      - name: Trigger comment workflow bad 
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          pr_number: ${{ steps.find-pr.outputs.pr_number }}
          message: >
            ${{
              steps.has_failed.outputs.exitcode == '1' && 'Pipeline has failed due to a decrease in performance in read' ||
              steps.has_failed.outputs.exitcode == '2' && 'Pipeline has failed due to a decrease in performance in write' ||
              steps.has_failed.outputs.exitcode == '3' && 'Pipeline has failed due to an increase for number of cycle' ||
             'Unknow error code'
            }}
